### ISSUE TITLE
安装pytorch3d报错

### ISSUE THREAD

**Issue by Kevin746p** [lipku/metahuman-stream#100]
系统:windows11
执行： pip install git+https://github.com/facebookresearch/pytorch3d.git"报错
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\projects\pytorch3d\setup.py", line 144, in <module>
    setup(
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\dist.py", line 968, in run_command
    super().run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\install.py", line 87, in run
    self.do_egg_install()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\dist.py", line 968, in run_command
    super().run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\dist.py", line 968, in run_command
    super().run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\dist.py", line 968, in run_command
    super().run_command(command)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
    _build_ext.run(self)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
    self.build_extensions()
  File "E:\projects\metahuman-stream\env\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\projects\metahuman-stream\env\lib\site-packages\Cython\Distutils\build_ext.py", line 127, in build_extension
    super(build_ext, self).build_extension(ext)
  File "E:\projects\metahuman-stream\env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "E:\projects\metahuman-stream\env\lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "E:\projects\metahuman-stream\env\lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "E:\projects\metahuman-stream\env\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by plore77** [comment]
https://zhuanlan.zhihu.com/p/627637604

**Comment by 2ezInCode** [comment]
建议最好不要用windows系统，直接上linux
