### ISSUE TITLE
window运行 ernerf 效果一直报错troch扩展编译异常

### ISSUE THREAD

**Issue by ShelikeSnow** [lipku/metahuman-stream#119]
![image](https://github.com/lipku/metahuman-stream/assets/110894108/0fea40a6-7a98-42b8-a852-0cd4bf374acc)
Traceback (most recent call last):
  File "E:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "E:\soft\anaconda\envs\metahuman-stream\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\project\metahuman-stream-main\ernerf\nerf_triplane\network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "E:\project\metahuman-stream-main\ernerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
  File "E:\project\metahuman-stream-main\ernerf\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "E:\project\metahuman-stream-main\ernerf\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "E:\project\metahuman-stream-main\ernerf\raymarching\backend.py", line 36, in <module>
    _backend = load(name='_raymarching_face',
  File "E:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "E:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching_face': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching_face -DTORCH_API_INCLUDE_EXTENSION_H -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\torch\csrc\api\include -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\TH -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IE:\soft\anaconda\envs\metahuman-stream\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -allow-unsupported-compiler -c E:\project\metahuman-stream-main\ernerf\raymarching\src\raymarching.cu -o raymarching.cuda.o 
FAILED: raymarching.cuda.o 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching_face -DTORCH_API_INCLUDE_EXTENSION_H -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\torch\csrc\api\include -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\TH -IE:\soft\anaconda\envs\metahuman-stream\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IE:\soft\anaconda\envs\metahuman-stream\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -allow-unsupported-compiler -c E:\project\metahuman-stream-main\ernerf\raymarching\src\raymarching.cu -o raymarching.cuda.o 

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1496): error: expected a "("
          detected during:
            instantiation of "void std::advance(_InIt &, _Diff) [with _InIt=const int64_t *, _Diff=std::_Iter_diff_t<const int64_t *>]" 
(1548): here
            instantiation of "_InIt std::next(_InIt, std::_Iter_diff_t<_InIt>) [with _InIt=const int64_t *]" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(1161): here
            instantiation of "void std::vector<_Ty, _Alloc>::_Assign_range(_Iter, _Iter, std::forward_iterator_tag) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>, _Iter=const int64_t *]" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(1210): here
            instantiation of "std::vector<_Ty, _Alloc> &std::vector<_Ty, _Alloc>::operator=(std::initializer_list<_Ty>) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>]" 
E:/soft/anaconda/envs/metahuman-stream/lib/site-packages/torch/include\ATen/core/jit_type.h(809): here

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1499): error: expected a "("
          detected during:
            instantiation of "void std::advance(_InIt &, _Diff) [with _InIt=const int64_t *, _Diff=std::_Iter_diff_t<const int64_t *>]" 
(1548): here
            instantiation of "_InIt std::next(_InIt, std::_Iter_diff_t<_InIt>) [with _InIt=const int64_t *]" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(1161): here
            instantiation of "void std::vector<_Ty, _Alloc>::_Assign_range(_Iter, _Iter, std::forward_iterator_tag) [with _Ty=int64_t, _Alloc=std::allocator<int64_t>, _Iter=const int64_t *]" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(1210): here

ninja: build stopped: subcommand failed.

**Comment by 2033723741** [comment]
same iisue...

**Comment by 2033723741** [comment]
ernerf文件夹下的freqencode, gridencode, raymarching, shencoder 单独编译(  python setup.py install )，然后再运行就不报错了

**Comment by licon** [comment]
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
error: command '/usr/local/cuda-11.5/bin/nvcc' failed with exit code 1


ernerf 文件夹下单独编译，报错，请问如何解决，是版本问题吗。
系统 ubuntu22
nvcc build cuda_11.5.r11.5/compiler.30672275_0
cuda 驱动版本：Driver Version: 535.183.01   CUDA Version: 12.2
