### ISSUE TITLE
运行python app.py --transport webrtc报ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lemwang** [lipku/metahuman-stream#146]
Traceback (most recent call last):
  File "/home/project/metahuman-stream/app.py", line 313, in <module>
    from ernerf.nerf_triplane.provider import NeRFDataset_Test
  File "/home/project/metahuman-stream/ernerf/nerf_triplane/provider.py", line 2, in <module>
    import cv2
  File "/root/anaconda3/envs/nerfstream/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/anaconda3/envs/nerfstream/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/root/anaconda3/envs/nerfstream/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by ccynet** [comment]
apt -y install libopencv-dev

**Comment by ccynet** [comment]
apt install libgl1-mesa-glx

**Comment by weweeeeee** [comment]
您好，我想问下，我看文档上写的是开端口tcp8010，udp50000-60000，udp需要开这么多吗，因为我这边是公司的电脑可能没法开这么多，有解决办法吗
