### ISSUE TITLE
Is MacOS supported？

### ISSUE THREAD

**Issue by Corsimy** [lipku/metahuman-stream#156]
Is MacOS supported？

**Comment by krmao** [comment]
```shell
(nerfstream) ➜  LiveTalking git:(main) python app.py
/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <F0D48035-EF9E-3141-9F63-566920E60D7C> /opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <ECC148AF-20FF-3EEE-BC75-4DD3E7455393> /opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/utils.py:171: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/utils.py:199: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/utils.py:230: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/utils.py:239: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/utils.py:248: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
Traceback (most recent call last):
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/raymarching/raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/SanDisk/Workspaces/LiveTalking/app.py", line 457, in <module>
    from nerfreal import NeRFReal,load_model,load_avatar
  File "/Volumes/SanDisk/Workspaces/LiveTalking/nerfreal.py", line 38, in <module>
    from ernerf.nerf_triplane.network import NeRFNetwork
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/nerf_triplane/renderer.py", line 10, in <module>
    from .. import raymarching
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/raymarching/__init__.py", line 1, in <module>
    from .raymarching import *
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/raymarching/raymarching.py", line 12, in <module>
    from .backend import _backend
  File "/Volumes/SanDisk/Workspaces/LiveTalking/ernerf/raymarching/backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1899, in _prepare_ldflags
    if (not os.path.exists(_join_cuda_home(extra_lib_dir)) and
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
(nerfstream) ➜  LiveTalking git:(main)
```
