### ISSUE TITLE
ImportError: DLL load failed while importing _raymarching_face: 找不到指定的模块。

### ISSUE THREAD

**Issue by tripledoors01** [lipku/metahuman-stream#183]
我跟着b站up主[晚安萤火虫h]配置项目环境，到运行app.py的时候就开始报这个错误，不知道怎么解决：

Traceback (most recent call last):
  File "D:\Desktop\Remake\metahuman-stream\ernerf\raymarching\raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ImportError: DLL load failed while importing _raymarching_face: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\Remake\metahuman-stream\app.py", line 332, in <module>
    from ernerf.nerf_triplane.network import NeRFNetwork
  File "D:\Desktop\Remake\metahuman-stream\ernerf\nerf_triplane\network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "D:\Desktop\Remake\metahuman-stream\ernerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
  File "D:\Desktop\Remake\metahuman-stream\ernerf\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\Desktop\Remake\metahuman-stream\ernerf\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\Desktop\Remake\metahuman-stream\ernerf\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1450, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1844, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing _raymarching_face: 找不到指定的模块。

**Comment by gojosatolu** [comment]
哥们问题解决了吗我还是没😭😭😭
