### ISSUE TITLE
转发模式启动报错：ValueError: Media sections in answer do not match offer

### ISSUE THREAD

**Issue by wssxx** [lipku/metahuman-stream#185]
使用转发模式启动，命令：
python app.py --listenport 6006 --transport rtcpush --push_url 'http://xxxx:1985/rtc/v1/whep/?app=live&stream=livestream'

start websocket server
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 397, in run_server
    loop.run_until_complete(run(opt.push_url))
  File "/root/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "app.py", line 165, in run
    await pc.setRemoteDescription(RTCSessionDescription(sdp=answer,type='answer'))
  File "/root/miniconda3/lib/python3.8/site-packages/aiortc/rtcpeerconnection.py", line 831, in setRemoteDescription
    self.__validate_description(description, is_local=False)
  File "/root/miniconda3/lib/python3.8/site-packages/aiortc/rtcpeerconnection.py", line 1300, in __validate_description
    raise ValueError("Media sections in answer do not match offer")
ValueError: Media sections in answer do not match offer

**Comment by BSPuppy** [comment]
Me too

**Comment by lipku** [comment]
--push_url 'http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream'

**Comment by wssxx** [comment]
> --push_url 'http://xxxx:1985/rtc/v1/whip/?app=live&stream=livestream'


已验证成功。我之前的push_url错了，whip写成了whep。 谢谢~

**Comment by wssxx** [comment]
已解决
