### ISSUE TITLE
srs 方式如何才能支持多个数字人对话？

### ISSUE THREAD

**Issue by fengxingshenzhou** [lipku/metahuman-stream#209]
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.096724s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.057590s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.048743s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.049337s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.051051s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.052273s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.048120s
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
Traceback (most recent call last):
  File "app.py", line 383, in <module>
    print("我看你生成几次")
  File "/root/metahuman-stream/nerfreal.py", line 61, in __init__
    self.asr = ASR(opt)
  File "/root/metahuman-stream/asrreal.py", line 46, in __init__
    self.model = AutoModelForCTC.from_pretrained(opt.asr_model).to(self.device)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2861, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.75 GiB total capacity; 9.47 GiB already allocated; 11.56 MiB free; 9.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

我把max_session改成了10 ，看日志他就加载了10次模型，直接干爆了，我是客服使用场景，肯定要打开多个客户端，请问这种该如何处理啊

**Comment by ivbydnlxgk** [comment]
老大是如何解决的

**Comment by khk111** [comment]
请问如何解决呢

**Comment by yzd1733638228** [comment]
大佬是如何解决的
