### ISSUE TITLE
raise asyncio.TimeoutError asyncio.exceptions.TimeoutError

### ISSUE THREAD

**Issue by KelvinHuang66** [lipku/metahuman-stream#235]
edgetts连续调用，协程会报错，任务会被终止掉，希望改进，例如捕获异常，保持任务完整执行。

**Comment by KelvinHuang66** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Metahuman_Stream/metahuman-stream1/ttsreal.py", line 56, in process_tts
    self.txt_to_audio(msg)
  File "/Metahuman_Stream/metahuman-stream1/ttsreal.py", line 82, in txt_to_audio
    asyncio.new_event_loop().run_until_complete(self.__main(voicename,text))
  File "/root/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Metahuman_Stream/metahuman-stream1/ttsreal.py", line 122, in __main
    async for chunk in communicate.stream():
  File "/root/miniconda3/lib/python3.8/site-packages/edge_tts/communicate.py", line 420, in stream
    async for received in websocket:
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/client_ws.py", line 312, in __anext__
    msg = await self.receive()
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/client_ws.py", line 244, in receive
    msg = await self._reader.read()
  File "/root/miniconda3/lib/python3.8/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/root/miniconda3/lib/python3.8/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by KelvinHuang66** [comment]
![image](https://github.com/user-attachments/assets/b731dab7-e5f2-47b7-be7a-8ec395686b87)

**Comment by KelvinHuang66** [comment]
> edgetts连续调用，协程会报错，任务会被终止掉，希望改进，例如捕获异常，保持任务完整执行。

**Comment by weweeeeee** [comment]
你好，请问这个问题你解决了吗，我也碰到了这个问题
