### ISSUE TITLE
接入LLM时报错

### ISSUE THREAD

**Issue by zjz0804** [lipku/metahuman-stream#254]
启动数字人后访问http://serverip:8010/rtcpushapi.html可以正确复读，但访问http://serverip:8010/rtcpushchat.html时出现以下报错：
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/data1/student/zjz/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
  File "/data1/student/zjz/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
  File "/data1/student/zjz/metahuman-stream/app.py", line 152, in human
    res=await asyncio.get_event_loop().run_in_executor(None, llm_response(params['text']))
  File "/data1/student/zjz/miniconda3/envs/nerfstream/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'str' object is not callable

**Comment by vasile-v1** [comment]
对不起，你的请求出错了，请再次尝试。
Sorry, your request has encountered an error. Please try again.

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/root/miniconda3/lib/python3.8/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "app.py", line 152, in human
    res=await asyncio.get_event_loop().run_in_executor(None, llm_response(params['text']))
  File "/root/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'str' object is not callable

无法调用vllm进行对话。
