### ISSUE TITLE
执行python app.py报错

### ISSUE THREAD

**Issue by OpenSorceYCW** [lipku/metahuman-stream#38]
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
详细报错信息如下：
[INFO] warm up ASR live model, expected latency = 1.400000s
start websocket server
[INFO] frame_to_text... 
Exception in thread Thread-2 (render):
Traceback (most recent call last):
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ycw/project/company/metahuman-stream/app.py", line 155, in render
    nerfreal.render()                  
  File "/home/ycw/project/company/metahuman-stream/nerfreal.py", line 155, in render
    self.asr.warm_up()
  File "/home/ycw/project/company/metahuman-stream/asrreal.py", line 445, in warm_up
    self.run_step()
  File "/home/ycw/project/company/metahuman-stream/asrreal.py", line 220, in run_step
    logits, labels, text = self.frame_to_text(inputs)
  File "/home/ycw/project/company/metahuman-stream/asrreal.py", line 341, in frame_to_text
    result = self.model(inputs.input_values.to(self.device))
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1969, in forward
    outputs = self.wav2vec2(
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1563, in forward
    hidden_states, extract_features = self.feature_projection(extract_features)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 487, in forward
    hidden_states = self.projection(norm_hidden_states)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ycw/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by ivoidcat** [comment]
+1

**Comment by xdujinsiyu** [comment]
可以直接去查看这个报错问题，两种方法，一个删除因为是CUBLAS相关的包，还有一个是环境变量的问题，csdn上有一个帖子很清楚，直接搜即可

**Comment by lwm345** [comment]
unset LD_LIBRARY_PATH
