### ISSUE TITLE
installation steps

### ISSUE THREAD

**Issue by shailesh-growexxer** [lipku/metahuman-stream#41]
which command should I execute to set up metahuman-stream using docker as readme file looks bit confusing?

**Comment by lipku** [comment]
3. Docker Run

**Comment by shailesh-growexxer** [comment]
Hi @lipku,
first I ran this docker command : docker run --gpus all -it --network=host --rm  registry.cn-hangzhou.aliyuncs.com/lipku/nerfstream:v1.3 to install all dependencies

then I ran docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5

and at the last I ran python app.py after resolving pytorch3d issue I am getting below error:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/metahuman-stream/app.py", line 17, in <module>
    from nerf_triplane.provider import NeRFDataset_Test
  File "/home/ec2-user/SageMaker/metahuman-stream/nerf_triplane/provider.py", line 16, in <module>
    from .utils import get_audio_features, get_rays, get_bg_coords, convert_poses
  File "/home/ec2-user/SageMaker/metahuman-stream/nerf_triplane/utils.py", line 32, in <module>
    import lpips
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/__init__.py", line 11, in <module>
    from lpips.lpips import *
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/lpips.py", line 9, in <module>
    from . import pretrained_networks as pn
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/pretrained_networks.py", line 3, in <module>
    from torchvision import models as tv
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 42, in <module>
    from torch.onnx._internal.fx import (
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/fx/__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/fx/patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/utils/generic.py", line 455, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'. Did you mean: '_register_pytree_node'?
has context menu

if anyone has any idea on how to solve this,please let me know. thanks in advance

**Comment by shailesh-growexxer** [comment]
> 3. Docker Run

If you are talking about running docker command which is in 3rd section,It ran successfully but I am not able to see the UI

**Comment by yslion** [comment]
> Hi @lipku, first I ran this docker command : docker run --gpus all -it --network=host --rm registry.cn-hangzhou.aliyuncs.com/lipku/nerfstream:v1.3 to install all dependencies
> 
> then I ran docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
> 
> and at the last I ran python app.py after resolving pytorch3d issue I am getting below error: Traceback (most recent call last): File "/home/ec2-user/SageMaker/metahuman-stream/app.py", line 17, in from nerf_triplane.provider import NeRFDataset_Test File "/home/ec2-user/SageMaker/metahuman-stream/nerf_triplane/provider.py", line 16, in from .utils import get_audio_features, get_rays, get_bg_coords, convert_poses File "/home/ec2-user/SageMaker/metahuman-stream/nerf_triplane/utils.py", line 32, in import lpips File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/**init**.py", line 11, in from lpips.lpips import * File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/lpips.py", line 9, in from . import pretrained_networks as pn File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/lpips/pretrained_networks.py", line 3, in from torchvision import models as tv File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/**init**.py", line 6, in from torchvision import datasets, io, models, ops, transforms, utils File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/models/**init**.py", line 2, in from .convnext import * File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in from ..ops.misc import Conv2dNormActivation, Permute File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/ops/**init**.py", line 1, in from ._register_onnx_ops import _register_custom_op File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in from torch.onnx import symbolic_opset11 as opset11 File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/**init**.py", line 46, in from ._internal.exporter import ( # usort:skip. needs to be last to avoid circular import File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 42, in from torch.onnx._internal.fx import ( File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/fx/**init**.py", line 1, in from .patcher import ONNXTorchPatcher File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/onnx/_internal/fx/patcher.py", line 11, in import transformers # type: ignore[import] File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/**init**.py", line 26, in from . import dependency_versions_check File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in from .utils.versions import require_version, require_version_core File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/utils/**init**.py", line 33, in from .generic import ( File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/transformers/utils/generic.py", line 455, in _torch_pytree.register_pytree_node( AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'. Did you mean: '_register_pytree_node'? has context menu
> 
> if anyone has any idea on how to solve this,please let me know. thanks in advance

I met the same issue  ,  chage transformer version to 4.28.0  works

**Comment by jeffreyhaoau** [comment]
命令有点复杂。求作者更新一下readme，加入傻瓜式启动程序的教程，谢谢。

**Comment by JerryDaHeLian** [comment]
> 命令有点复杂。求作者更新一下readme，加入傻瓜式启动程序的教程，谢谢。

附议！
