### ISSUE TITLE
 fatal error C1189: #error:  You need C++17 to compile PyTorch nvcc warning : incompatible redefinition for option 'std', the last value of this option was used freqencoder.cu ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by mbt1909432** [lipku/metahuman-stream#65]
(nerfstream) F:\VirtualMan\metahuman-stream-main\freqencoder>python setup.py install
running install
D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing freqencoder.egg-info\PKG-INFO
writing dependency_links to freqencoder.egg-info\dependency_links.txt
writing top-level names to freqencoder.egg-info\top_level.txt
reading manifest file 'freqencoder.egg-info\SOURCES.txt'
writing manifest file 'freqencoder.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py:418: UserWarning: The detected CUDA version (12.4) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building '_freqencoder' extension
D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Emitting ninja build file F:\VirtualMan\metahuman-stream-main\freqencoder\build\temp.win-amd64-cpython-310\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\nvcc --generate-dependencies-with-compile --dependency-output F:\VirtualMan\metahuman-stream-main\freqencoder\build\temp.win-amd64-cpython-310\Release\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include" -ID:\Anaconda\envs\nerfstream\include -ID:\Anaconda\envs\nerfstream\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IE:\Windows Kits\10\include\10.0.22621.0\ucrt" "-IE:\Windows Kits\10\\include\10.0.22621.0\\um" "-IE:\Windows Kits\10\\include\10.0.22621.0\\shared" "-IE:\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IE:\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c F:\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.cu -o F:\VirtualMan\metahuman-stream-main\freqencoder\build\temp.win-amd64-cpython-310\Release\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
FAILED: F:/VirtualMan/metahuman-stream-main/freqencoder/build/temp.win-amd64-cpython-310/Release/VirtualMan/metahuman-stream-main/freqencoder/src/freqencoder.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\nvcc --generate-dependencies-with-compile --dependency-output F:\VirtualMan\metahuman-stream-main\freqencoder\build\temp.win-amd64-cpython-310\Release\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\nerfstream\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include" -ID:\Anaconda\envs\nerfstream\include -ID:\Anaconda\envs\nerfstream\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IE:\Windows Kits\10\include\10.0.22621.0\ucrt" "-IE:\Windows Kits\10\\include\10.0.22621.0\\um" "-IE:\Windows Kits\10\\include\10.0.22621.0\\shared" "-IE:\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IE:\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c F:\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.cu -o F:\VirtualMan\metahuman-stream-main\freqencoder\build\temp.win-amd64-cpython-310\Release\VirtualMan\metahuman-stream-main\freqencoder\src\freqencoder.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF2_OPERATORS__”(用“/U__CUDA_NO_HALF2_OPERATORS__”)
freqencoder.cu
D:/Anaconda/envs/nerfstream/lib/site-packages/torch/include\c10/util/C++17.h(24): fatal error C1189: #error:  You need C++17 to compile PyTorch
nvcc warning : incompatible redefinition for option 'std', the last value of this option was used
freqencoder.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "D:\Anaconda\envs\nerfstream\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\VirtualMan\metahuman-stream-main\freqencoder\setup.py", line 40, in <module>
    setup(
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\install.py", line 84, in run
    self.do_egg_install()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
    _build_ext.run(self)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\Anaconda\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by orzlenmo** [comment]
#1  可以参考这层的，我也报这个错，根据这个里面的吧c++14改成c++17就好了

**Comment by wxzz** [comment]
我也是报的这个错误。https://github.com/lipku/metahuman-stream/issues/182
