### ISSUE TITLE
webRtc使用问题

### ISSUE THREAD

**Issue by Pilot-Labs-Dev** [lipku/metahuman-stream#77]
请问如果不使用rtmp推流，是不是可以不运行：
docker run --rm --env CANDIDATE=$CANDIDATE \
  -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp \
  registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 \
  objs/srs -c conf/rtc.conf

而是直接运行 python app.py --transport webrtc
浏览器输入http://serverip:8010/webrtc.html

按照上述指令运行后结果如下：
app打印：
Traceback (most recent call last):
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\gevent\pywsgi.py", line 1107, in handle_one_response
    self.run_application()
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\geventwebsocket\handler.py", line 75, in run_application
    self.run_websocket()
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\geventwebsocket\handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "e:\Users\admin\anaconda3\envs\nerfreal\lib\site-packages\werkzeug\routing\map.py", line 627, in match
    raise WebsocketMismatch() from None
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2024-05-07T03:28:18Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '64495', 'HTTP_HOST': '127.0.0.1:8000', (hidden keys: 30)} failed with WebsocketMismatch

网页控制台能看到websocket connected，然后马上就closed，error code：1005。请问docker是一定要运行的吗？还是不需要docker可以独立运行webrtc？

**Comment by Pilot-Labs-Dev** [comment]
修改python/site-packages/flask_sockets.py，将
self.url_map.add(Rule(rule, endpoint=f)) 改成  
self.url_map.add(Rule(rule, endpoint=f, websocket=True))       

解决。

**Comment by weibiaoyi** [comment]
需要运行docker



在 2024-05-07 11:50:12，"Pilot-Labs-Dev" ***@***.***> 写道：

请问如果不使用rtmp推流，是不是可以不运行：
docker run --rm --env CANDIDATE=$CANDIDATE
-p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp
registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
objs/srs -c conf/rtc.conf

而是直接运行 python app.py --transport webrtc
浏览器输入http://serverip:8010/webrtc.html即可？
网页控制台能看到websocket connected，然后马上就closed，error code：1005。请问docker是一定要运行的吗？还是不需要docker可以独立运行webrtc？

**Comment by mkygogo** [comment]
> 修改python/site-packages/flask_sockets.py，将 self.url_map.add(Rule(rule, endpoint=f)) 改成 self.url_map.add(Rule(rule, endpoint=f, websocket=True))
> 
> 解决。


修改的这个文件具体位置在哪里啊？

**Comment by gokula-krishna-dev** [comment]
> Modify python/site-packages/flask_sockets.py and change self.url_map.add(Rule(rule, endpoint=f)) to self.url_map.add(Rule(rule, endpoint=f, websocket=True))
> 
> solve.

我试过了这个方法，但没有解决问题。有人有解决办法吗？
