### ISSUE TITLE
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

### ISSUE THREAD

**Issue by weibiaoyi** [lipku/metahuman-stream#80]
Traceback (most recent call last):
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/gevent/pywsgi.py", line 1107, in handle_one_response
    self.run_application()
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/home/anaconda3/envs/nerfstream/lib/python3.10/site-packages/werkzeug/routing/map.py", line 627, in match
    raise WebsocketMismatch() from None
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2024-05-08T08:08:36Z {'REMOTE_ADDR': '192.168.31.110', 'REMOTE_PORT': '8041', 'HTTP_HOST': '192.168.31.204:8000', (hidden keys: 31)} failed with WebsocketMismatch

**Comment by weibiaoyi** [comment]
有大佬遇到过这个问题吗

**Comment by Yang-HangWA** [comment]
遇到了同样的问题 
```
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2024-05-16T13:28:51Z {'REMOTE_ADDR': '10.8.80.50', 'REMOTE_PORT': '52002', 'HTTP_HOST': '10.8.80.220:8000', (hidden keys: 31)} failed with WebsocketMismatch
```

**Comment by YPwan** [comment]
did you fix it? i meet the same question.

**Comment by lipku** [comment]
看faq
