### ISSUE TITLE
运行python app.py报错

### ISSUE THREAD

**Issue by mkygogo** [lipku/metahuman-stream#82]
错误如下：
Error: Cannot connect to host localhost:1985 ssl:default [Connect call failed ('127.0.0.1', 1985)]
Exception in thread Thread-4 (run_server):
Traceback (most recent call last):
  File "/miniconda3/envs/nerfstream/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/miniconda3/envs/nerfstream/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/metahumanstream/app.py", line 535, in run_server
    loop.run_until_complete(run(opt.push_url))
  File "/miniconda3/envs/nerfstream/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/metahumanstream/app.py", line 321, in run
    await pc.setRemoteDescription(RTCSessionDescription(sdp=answer,type='answer'))
  File "/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiortc/rtcpeerconnection.py", line 829, in setRemoteDescription
    description = sdp.SessionDescription.parse(sessionDescription.sdp)
  File "/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiortc/sdp.py", line 385, in parse
    session_lines, media_groups = grouplines(sdp)
  File "/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiortc/sdp.py", line 141, in grouplines
    for line in sdp.splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by sukilexi** [comment]
如何解决？

**Comment by fjesikfjdskl** [comment]
+1

**Comment by shubihu** [comment]
需要先开启srs
```
export CANDIDATE='<服务器外网ip>'
docker run --rm --env CANDIDATE=$CANDIDATE \
  -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp \
  registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 \
  objs/srs -c conf/rtc.conf
```

**Comment by charles4song** [comment]
> 需要先开启srs
> 
> ```
> export CANDIDATE='<服务器外网ip>'
> docker run --rm --env CANDIDATE=$CANDIDATE \
>   -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp \
>   registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 \
>   objs/srs -c conf/rtc.conf
> ```

已经开启了srs，还是这个异常。

**Comment by zhaofeng3012** [comment]
> 需要先开启srs
> 
> ```
> export CANDIDATE='<服务器外网ip>'
> docker run --rm --env CANDIDATE=$CANDIDATE \
>   -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp \
>   registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 \
>   objs/srs -c conf/rtc.conf
> ```

您好，咨询一下这部分是要在另一台有公网IP的云服务器上启动的srs吗？
export CANDIDATE='<服务器外网ip>'   这里的服务器外网ip是指启动srs服务的机器本身的公网ip？还是指运行数字人生成的GPU服务器的公网ip？
