### ISSUE TITLE
mac M1芯片如何支持？

### ISSUE THREAD

**Issue by manwangbin** [lipku/metahuman-stream#95]
mac M1芯片无法安装cuda，所以在启动的时候抛出：
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/app.py", line 25, in <module>
    from ernerf.nerf_triplane.network import NeRFNetwork
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/ernerf/nerf_triplane/network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/ernerf/nerf_triplane/renderer.py", line 10, in <module>
    from .. import raymarching
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/ernerf/raymarching/__init__.py", line 1, in <module>
    from .raymarching import *
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/ernerf/raymarching/raymarching.py", line 12, in <module>
    from .backend import _backend
  File "/Users/wangbin/Work/tuweisoft/aishop/metahuman-stream/ernerf/raymarching/backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1809, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1901, in _prepare_ldflags
    if (not os.path.exists(_join_cuda_home(extra_lib_dir)) and
  File "/opt/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by lipku** [comment]
需要nvidia显卡，mac运行不了
