### ISSUE TITLE
Failed to build raymarching-face

### ISSUE THREAD

**Issue by sukilexi** [lipku/metahuman-stream#98]
似乎不是C++17的问题
我的cuda版本是11.3
torch也是
但无法构建raymarching这些，下面是我的报错，大佬能帮我看看吗？  

Building wheel for raymarching-face (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching
      creating /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src
      Emitting ninja build file /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] /usr/local/cuda-11.3/bin/nvcc  -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/TH -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/pikapikaq/anaconda3/envs/ernerf/include/python3.10 -c -c '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/raymarching.cu' -o '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/raymarching.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching_face -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/raymarching.o
      /usr/local/cuda-11.3/bin/nvcc  -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/TH -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/pikapikaq/anaconda3/envs/ernerf/include/python3.10 -c -c '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/raymarching.cu' -o '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/raymarching.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching_face -D_GLIBCXX_USE_CXX11_ABI=0
      gcc: error trying to exec 'cc1plus': execvp: 没有那个文件或目录
      nvcc fatal   : Failed to preprocess host compiler properties.
      [2/2] c++ -MMD -MF '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/bindings.o'.d -pthread -B /home/pikapikaq/anaconda3/envs/ernerf/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/pikapikaq/anaconda3/envs/ernerf/include -fPIC -O2 -isystem /home/pikapikaq/anaconda3/envs/ernerf/include -fPIC -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/TH -I/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/pikapikaq/anaconda3/envs/ernerf/include/python3.10 -c -c '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/bindings.cpp' -o '/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/build/temp.linux-x86_64-3.10/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/src/bindings.o' -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_raymarching_face -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/pikapikaq/桌面/wyl/metahuman-stream/ernerf/raymarching/setup.py", line 45, in <module>
          setup(
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/pikapikaq/anaconda3/envs/ernerf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching-face
  Running setup.py clean for raymarching-face
Failed to build raymarching-face
ERROR: Could not build wheels for raymarching-face, which is required to install pyproject.toml-based projects

**Comment by FaoGuck** [comment]
请问您解决了嘛，我也是一样的问题

**Comment by zhangshulin12** [comment]
请问解决了吗  ?
